name: Prerelease Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version
        id: get-version
        run: echo "version=$(node -p "require('./lib/package.json').version")" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: cd lib && npm install

      - name: Build package
        run: cd lib && npm run build

      - name: Generate prerelease version
        id: prerelease-version
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/-/g')
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          PRERELEASE_VERSION="${{ steps.get-version.outputs.version }}-${BRANCH_NAME}.${TIMESTAMP}"
          echo "prerelease_version=${PRERELEASE_VERSION}" >> $GITHUB_OUTPUT
          # Update package.json with prerelease version
          cd lib && npm version ${PRERELEASE_VERSION} --no-git-tag-version
          
      - name: Publish prerelease to NPM
        run: cd lib && npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
