name: Prerelease Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: cd lib && npm ci

      - name: Build package
        run: cd lib && npm run build

      - name: Run tests (if available)
        run: cd lib && npm test || echo "No tests available"
        continue-on-error: true